PROG6_BeestjeOpJeFeestje/Controllers/AnimalController.cs
using AutoMapper;
using Domain.Models;
using Domain.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PROG6_BeestjeOpJeFeestje.ViewModels;

namespace PROG6_BeestjeOpJeFeestje.Controllers;

public class AnimalController : Controller
{
    private readonly IAnimalRepository _animalRepository;
    private readonly IMapper _mapper;

    public AnimalController(IAnimalRepository animalRepository, IMapper mapper)
    {
        _animalRepository = animalRepository;
        _mapper = mapper;
    }

    // GET: Animal
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Index()
    {
        var animals = await _animalRepository.GetAllAnimals();
        return View(animals);
    }

    // GET: Animal/Details/5
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Details(int id)
    {
        var animal = await _animalRepository.GetAnimalByIdOrNull(id);
        if (animal == null) return NotFound();

        return View(animal);
    }

    // GET: Animal/Create
    [Authorize(Policy = "AdminOnly")]
    public ActionResult Create()
    {
        return View();
    }

    // POST: Animal/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Create([Bind("Name,Type,Price,ImageUrl,IsVip")] AnimalCreateVM animal)
    {
        if (ModelState.IsValid)
        {
            Animal model = _mapper.Map<Animal>(animal);
            await _animalRepository.AddAnimal(model);
            return RedirectToAction(nameof(Index));
        }

        return View(animal);
    }

    // GET: Animal/Edit/5
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Edit(int id)
    {
        var animal = await _animalRepository.GetAnimalByIdOrNull(id);
        if (animal == null) return NotFound();
        
        
        return View(animal);
    }

    // POST: Animal/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Type,Price,ImageUrl,IsVip")] Animal model)
    {
        if (id != model.Id) return NotFound();

        if (!ModelState.IsValid) return View(model);

        try
        {
            await _animalRepository.UpdateAnimal(model);
        }
        catch
        {
            if (!_animalRepository.AnimalExists(model.Id).Result)
                return NotFound();
            throw;
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: Animal/Delete/5
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Delete(int id)
    {

        var animal = await _animalRepository.GetAnimalByIdOrNull(id);
        if (animal == null) return NotFound();

        return View(animal);
    }

    // POST: Animal/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _animalRepository.DeleteAnimal(id);
        return RedirectToAction(nameof(Index));
    }
}

PROG6_BeestjeOpJeFeestje/Controllers/UserController.cs
using AutoMapper;
using Domain.Data;
using Domain.Models;
using Domain.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PROG6_BeestjeOpJeFeestje.ViewModels;

namespace PROG6_BeestjeOpJeFeestje.Controllers;

public class UserController : Controller
{
    private readonly IMapper _mapper;
    private readonly IUserRepository _userRepository;

    public UserController(IMapper mapper, IUserRepository userRepository)
    {
        _mapper = mapper;
        _userRepository = userRepository;
    }

    // GET: User
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Index()
    {
        var users = await _userRepository.GetAllUsers();
        return View(users);
    }

    // GET: User/Details/5
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Details(string? id)
    {
        if (id == null) return NotFound();

        var user = await _userRepository.GetUserByIdOrNull(id);
        if (user == null) return NotFound();

        return View(user);
    }

    // GET: User/Create
    [Authorize(Policy = "AdminOnly")]
    public ActionResult Create()
    {
        return View();
    }

    // POST: User/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Create([Bind("FirstName,InBetween,LastName,Address,Email,PhoneNumber,MemberCard")] UserCreateVM user)
    {
        if (ModelState.IsValid)
        {
            User model = _mapper.Map<User>(user);
            model.UserName = user.Email;
            model.NormalizedUserName = user.Email.ToUpper();
            model.NormalizedEmail = user.Email.ToUpper();
            await _userRepository.AddUser(model);
            return RedirectToAction(nameof(UserPassword), new {id = model.Id});
        }

        return View(user);
    }
    
    [HttpGet]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> UserPassword(string? id)
    {
        
        if (id == null) return NotFound();
        
        var model = await _userRepository.GetUserByIdOrNull(id);

        if (model == null) return NotFound();
        
        var user = _mapper.Map<UserPasswordVM>(model);

        string password = GeneratePassword();
        var pass = new PasswordHasher<object>().HashPassword(user, password);
        
        user.Password = password;
        model.PasswordHash = pass;
        
        await _userRepository.UpdateUser(model);
        
        return View(user);
        
    }

    // GET: User/Edit/5
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Edit(string? id)
    {
        if (id == null) return NotFound();

        var user = await _userRepository.GetUserByIdOrNull(id);
        if (user == null) return NotFound();
        
        
        return View(user);
    }

    // POST: User/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Edit(string id, [Bind("Id,FirstName,InBetween,LastName,Address,MemberCard")] User model)
    {
        if (id != model.Id) return NotFound();

        if (!ModelState.IsValid) return View(model);

        try
        {
            await _userRepository.UpdateUser(model);
        }
        catch
        {
            if (!_userRepository.UserExists(model.Id).Result)
                return NotFound();
            throw;
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: User/Delete/5
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> Delete(string? id)
    {
        if (id == null) return NotFound();

        var user = await _userRepository.GetUserByIdOrNull(id);
        if (user == null) return NotFound();

        return View(user);
    }

    // POST: User/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Policy = "AdminOnly")]
    public async Task<IActionResult> DeleteConfirmed(string id)
    {
        await _userRepository.DeleteUser(id);
        return RedirectToAction(nameof(Index));
    }
    
    private string GeneratePassword()
    {
        const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*()_+=-<>?/.,;:[]{}";
        var stringChars = new char[8];
        var random = new Random();

        for (int i = 0; i < stringChars.Length; i++)
        {
            stringChars[i] = chars[random.Next(chars.Length)];
        }

        return new string(stringChars);
    }
}

PROG6_BeestjeOpJeFeestje/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PROG6_BeestjeOpJeFeestje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PROG6_BeestjeOpJeFeestje.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PROG6_BeestjeOpJeFeestje</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Animals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    }
                    
                    @if (SignInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Bookings</a>
                                </li>
                            } else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-route-user="@User.Identity?.Name" asp-action="IndexForUser">Bookings</a>
                                    </li>
                                }
                        } else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="SetDate">Bookings</a>
                                </li>
                            }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - PROG6_BeestjeOpJeFeestje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>